[2025-01-06T13:25:10.212+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: insert_date.call_get_posting_data_by_date manual__2025-01-06T13:12:11.564960+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
