[2025-01-12T20:13:04.883+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_date.sql_ft_balance_f manual__2025-01-12T20:12:51.184953+00:00 [queued]>
[2025-01-12T20:13:04.897+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_date.sql_ft_balance_f manual__2025-01-12T20:12:51.184953+00:00 [queued]>
[2025-01-12T20:13:04.898+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-12T20:13:05.073+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): sql_ft_balance_f> on 2025-01-12 20:12:51.184953+00:00
[2025-01-12T20:13:05.079+0000] {standard_task_runner.py:60} INFO - Started process 8781 to run task
[2025-01-12T20:13:05.083+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_date', 'sql_ft_balance_f', 'manual__2025-01-12T20:12:51.184953+00:00', '--job-id', '2937', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp023tj8gg']
[2025-01-12T20:13:05.086+0000] {standard_task_runner.py:88} INFO - Job 2937: Subtask sql_ft_balance_f
[2025-01-12T20:13:05.144+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_date.sql_ft_balance_f manual__2025-01-12T20:12:51.184953+00:00 [running]> on host 711845a6becd
[2025-01-12T20:13:05.238+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='budanovsa' AIRFLOW_CTX_DAG_ID='insert_date' AIRFLOW_CTX_TASK_ID='sql_ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T20:12:51.184953+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-12T20:12:51.184953+00:00'
[2025-01-12T20:13:05.239+0000] {sql.py:276} INFO - Executing: INSERT INTO ds.ft_balance_f(
      account_rk
    , currency_rk
    , balance_out
    , on_date
)
SELECT fbf."ACCOUNT_RK" 
     , fbf."CURRENCY_RK" 
     , fbf."BALANCE_OUT" 
     , to_date(fbf."ON_DATE" , 'dd.mm.YYYY') AS on_date
FROM stage.ft_balance_f fbf
WHERE fbf."ACCOUNT_RK"  IS NOT NULL
  AND fbf."ON_DATE"  IS NOT NULL
ON conflict On Constraint ft_balance_f_pkey DO Update
  set currency_rk=excluded.currency_rk
		,balance_out=excluded.balance_out;

[2025-01-12T20:13:05.248+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T20:13:05.258+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T20:13:05.324+0000] {sql.py:450} INFO - Running statement: INSERT INTO ds.ft_balance_f(
      account_rk
    , currency_rk
    , balance_out
    , on_date
)
SELECT fbf."ACCOUNT_RK" 
     , fbf."CURRENCY_RK" 
     , fbf."BALANCE_OUT" 
     , to_date(fbf."ON_DATE" , 'dd.mm.YYYY') AS on_date
FROM stage.ft_balance_f fbf
WHERE fbf."ACCOUNT_RK"  IS NOT NULL
  AND fbf."ON_DATE"  IS NOT NULL
ON conflict On Constraint ft_balance_f_pkey DO Update
  set currency_rk=excluded.currency_rk
		,balance_out=excluded.balance_out;
, parameters: None
[2025-01-12T20:13:05.331+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.CardinalityViolation: ОШИБКА:  команда ON CONFLICT DO UPDATE не может подействовать на строку дважды
HINT:  Проверьте, не содержат ли строки, которые должна добавить команда, дублирующиеся значения, подпадающие под ограничения.

[2025-01-12T20:13:05.341+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=insert_date, task_id=sql_ft_balance_f, execution_date=20250112T201251, start_date=20250112T201304, end_date=20250112T201305
[2025-01-12T20:13:05.358+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2937 for task sql_ft_balance_f (ОШИБКА:  команда ON CONFLICT DO UPDATE не может подействовать на строку дважды
HINT:  Проверьте, не содержат ли строки, которые должна добавить команда, дублирующиеся значения, подпадающие под ограничения.
; 8781)
[2025-01-12T20:13:05.377+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-01-12T20:13:05.409+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
