[2025-01-07T11:40:20.307+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_date.sql_md_account_d manual__2025-01-07T09:51:57.372350+00:00 [queued]>
[2025-01-07T11:40:20.314+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_date.sql_md_account_d manual__2025-01-07T09:51:57.372350+00:00 [queued]>
[2025-01-07T11:40:20.314+0000] {taskinstance.py:2170} INFO - Starting attempt 13 of 14
[2025-01-07T11:40:20.431+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): sql_md_account_d> on 2025-01-07 09:51:57.372350+00:00
[2025-01-07T11:40:20.436+0000] {standard_task_runner.py:60} INFO - Started process 2139 to run task
[2025-01-07T11:40:20.439+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_date', 'sql_md_account_d', 'manual__2025-01-07T09:51:57.372350+00:00', '--job-id', '792', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpe3nsbp8q']
[2025-01-07T11:40:20.441+0000] {standard_task_runner.py:88} INFO - Job 792: Subtask sql_md_account_d
[2025-01-07T11:40:20.477+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_date.sql_md_account_d manual__2025-01-07T09:51:57.372350+00:00 [running]> on host 25a397655cc7
[2025-01-07T11:40:20.536+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='budanovsa' AIRFLOW_CTX_DAG_ID='insert_date' AIRFLOW_CTX_TASK_ID='sql_md_account_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T09:51:57.372350+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T09:51:57.372350+00:00'
[2025-01-07T11:40:20.537+0000] {sql.py:276} INFO - Executing: INSERT INTO dsl.md_account_d( 
     data_actual_date
    ,data_actual_end_date
    ,account_rk
    ,account_number
    ,char_type
	,currency_rk
	,currency_code
)
SELECT
      to_date(mad."DATA_ACTUAL_DATE", 'dd-mm-YYYY') 
    , to_date(mad."DATA_ACTUAL_END_DATE", 'dd.mm.YYYY')
    , mad."ACCOUNT_RK"
    , SUBSTRING(mad."ACCOUNT_NUMBER", 3)::BIGINT
	, mad."CHAR_TYPE"
	, mad."CURRENCY_RK"
	, mad."CURRENCY_CODE"
  FROM stage.md_account_d mad
 WHERE mad."DATA_ACTUAL_DATE" IS NOT NULL
   AND mad."DATA_ACTUAL_END_DATE" IS NOT NULL
   AND mad."ACCOUNT_RK" IS NOT NULL
   AND mad."ACCOUNT_NUMBER" IS NOT NULL
   AND mad."CHAR_TYPE" IS NOT NULL
   AND mad."CURRENCY_RK" IS NOT NULL
   AND mad."CURRENCY_CODE" IS NOT NULL; 



[2025-01-07T11:40:20.543+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-07T11:40:20.550+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-07T11:40:20.701+0000] {sql.py:450} INFO - Running statement: INSERT INTO dsl.md_account_d( 
     data_actual_date
    ,data_actual_end_date
    ,account_rk
    ,account_number
    ,char_type
	,currency_rk
	,currency_code
)
SELECT
      to_date(mad."DATA_ACTUAL_DATE", 'dd-mm-YYYY') 
    , to_date(mad."DATA_ACTUAL_END_DATE", 'dd.mm.YYYY')
    , mad."ACCOUNT_RK"
    , SUBSTRING(mad."ACCOUNT_NUMBER", 3)::BIGINT
	, mad."CHAR_TYPE"
	, mad."CURRENCY_RK"
	, mad."CURRENCY_CODE"
  FROM stage.md_account_d mad
 WHERE mad."DATA_ACTUAL_DATE" IS NOT NULL
   AND mad."DATA_ACTUAL_END_DATE" IS NOT NULL
   AND mad."ACCOUNT_RK" IS NOT NULL
   AND mad."ACCOUNT_NUMBER" IS NOT NULL
   AND mad."CHAR_TYPE" IS NOT NULL
   AND mad."CURRENCY_RK" IS NOT NULL
   AND mad."CURRENCY_CODE" IS NOT NULL; 


, parameters: None
[2025-01-07T11:40:20.705+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DatetimeFieldOverflow: ОШИБКА:  значение поля типа date/time вне диапазона: "2018-01-01"

[2025-01-07T11:40:20.713+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=insert_date, task_id=sql_md_account_d, execution_date=20250107T095157, start_date=20250107T114020, end_date=20250107T114020
[2025-01-07T11:40:20.724+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 792 for task sql_md_account_d (ОШИБКА:  значение поля типа date/time вне диапазона: "2018-01-01"
; 2139)
[2025-01-07T11:40:20.733+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-01-07T11:40:20.753+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
