[2025-01-27T20:16:55.842+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_date.split manual__2025-01-27T20:16:51.846211+00:00 [queued]>
[2025-01-27T20:16:55.853+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_date.split manual__2025-01-27T20:16:51.846211+00:00 [queued]>
[2025-01-27T20:16:55.854+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-27T20:16:55.974+0000] {taskinstance.py:2191} INFO - Executing <Task(EmptyOperator): split> on 2025-01-27 20:16:51.846211+00:00
[2025-01-27T20:16:55.979+0000] {standard_task_runner.py:60} INFO - Started process 1348 to run task
[2025-01-27T20:16:55.982+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'import_date', 'split', 'manual__2025-01-27T20:16:51.846211+00:00', '--job-id', '3309', '--raw', '--subdir', 'DAGS_FOLDER/import_date.py', '--cfg-path', '/tmp/tmpinrieccs']
[2025-01-27T20:16:55.985+0000] {standard_task_runner.py:88} INFO - Job 3309: Subtask split
[2025-01-27T20:16:56.026+0000] {task_command.py:423} INFO - Running <TaskInstance: import_date.split manual__2025-01-27T20:16:51.846211+00:00 [running]> on host 711845a6becd
[2025-01-27T20:16:56.097+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='budanovsa' AIRFLOW_CTX_DAG_ID='import_date' AIRFLOW_CTX_TASK_ID='split' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T20:16:51.846211+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T20:16:51.846211+00:00'
[2025-01-27T20:16:56.107+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=import_date, task_id=split, execution_date=20250127T201651, start_date=20250127T201655, end_date=20250127T201656
[2025-01-27T20:16:56.107+0000] {taskinstance.py:1116} ERROR - Error when executing uploading_logs callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1113, in _run_finished_callback
    callback(context)
TypeError: uploading_logs() takes 0 positional arguments but 1 was given
[2025-01-27T20:16:56.155+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-27T20:16:56.176+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
