[2025-01-12T14:04:19.425+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_date.create_log_sheme manual__2025-01-12T14:04:16.428913+00:00 [queued]>
[2025-01-12T14:04:19.441+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_date.create_log_sheme manual__2025-01-12T14:04:16.428913+00:00 [queued]>
[2025-01-12T14:04:19.441+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-12T14:04:19.640+0000] {taskinstance.py:2191} INFO - Executing <Task(SQLExecuteQueryOperator): create_log_sheme> on 2025-01-12 14:04:16.428913+00:00
[2025-01-12T14:04:19.648+0000] {standard_task_runner.py:60} INFO - Started process 2025 to run task
[2025-01-12T14:04:19.652+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_date', 'create_log_sheme', 'manual__2025-01-12T14:04:16.428913+00:00', '--job-id', '2207', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp8eqamfdb']
[2025-01-12T14:04:19.656+0000] {standard_task_runner.py:88} INFO - Job 2207: Subtask create_log_sheme
[2025-01-12T14:04:19.720+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_date.create_log_sheme manual__2025-01-12T14:04:16.428913+00:00 [running]> on host 711845a6becd
[2025-01-12T14:04:19.835+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='budanovsa' AIRFLOW_CTX_DAG_ID='insert_date' AIRFLOW_CTX_TASK_ID='create_log_sheme' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T14:04:16.428913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-12T14:04:16.428913+00:00'
[2025-01-12T14:04:19.837+0000] {sql.py:276} INFO - Executing: create schema if not exists "log";

create table if not exists
	log.logt (
		execution_datetime TIMESTAMP not null,
		event_datetime TIMESTAMP not null,
		event_name VARCHAR(30) not null
);
[2025-01-12T14:04:19.850+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T14:04:19.864+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T14:04:19.961+0000] {sql.py:450} INFO - Running statement: create schema if not exists "log";

create table if not exists
	log.logt (
		execution_datetime TIMESTAMP not null,
		event_datetime TIMESTAMP not null,
		event_name VARCHAR(30) not null
);, parameters: None
[2025-01-12T14:04:19.994+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_date, task_id=create_log_sheme, execution_date=20250112T140416, start_date=20250112T140419, end_date=20250112T140419
[2025-01-12T14:04:19.999+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-12T14:04:20.081+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO log.logt (execution_datetime, event_datetime, event_name)
        VALUES ('2025-01-12 14:04:16.428913', '2025-01-12 14:04:19.994953', 'create_log_sheme');
    , parameters: None
[2025-01-12T14:04:20.093+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-12T14:04:20.095+0000] {taskinstance.py:1116} ERROR - Error when executing uploading_logs callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1113, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/insert_data.py", line 54, in uploading_logs
    time.sleep(5)
AttributeError: 'builtin_function_or_method' object has no attribute 'sleep'
[2025-01-12T14:04:20.146+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-12T14:04:20.204+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
